version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_mqtt
    ports:
      - "5672:5672"    # Porta padrão AMQP
      - "15672:15672"  # Porta do RabbitMQ Management UI
      - "1883:1883"    # Porta padrão MQTT
      - "8883:8883"    # Porta MQTT sobre TLS (opcional)
    environment:
      RABBITMQ_DEFAULT_USER: usuario
      RABBITMQ_DEFAULT_PASS: senha
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf # Arquivo de configuração do RabbitMQ
    command: >
      bash -c "
      rabbitmq-plugins enable --offline rabbitmq_mqtt &&
      rabbitmq-plugins enable --offline rabbitmq_management &&
      rabbitmq-server
      "
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge

volumes:
  rabbitmq_data:
